name: render README
on:
  push:
    branches: master

jobs:
  render:
    name: Render README.md
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Render README.md
        run: python render.py
      - name: commit rendered README
        run: |
          git add README.md
          git commit -m "Re-build README.md" || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
